language: java

addons:
  postgresql: "9.3"
  
python:
  - "2.7"

env:
  - MAVEN_OPTS=-Xmx1024M


before_install:
  - echo whoami
  - echo java -version
  - echo python --version
  - echo `pwd`
  - "cd config && cp local.conf.dist local.conf && cd .."
  - "cd scripts"
  - make create_databases
  - make setup
  - make new_deploy

install:

before_script:

script:
  - echo `pwd`
  - "make compile"