language: java

python:
  - "2.7"

env:
  - MAVEN_OPTS=-Xmx1024M


before_install:
  - echo whoami
  - echo java -version
  - echo python --version
  - echo `pwd`
  - "cd config && cp local.conf.dist local.conf && cd .."


install:

before_script:

script:
  - echo `pwd`
  - "cd scripts && make compile"