language: java

python:
  - "2.7"

env:
  - MAVEN_OPTS=-Xmx1024M


before_install:
  - whoami
  - java -version
  - python --version
  - "cd config && cp local.conf.dist local.conf"


install:

before_script:

script:
  - "cd scripts && make compile"