language: java

addons:
  postgresql: "9.3"

python:
  - "2.7"

env:
  - MAVEN_OPTS=-Xmx1024M


before_install:
  - whoami
  - java -version
  - python --version
  - pwd
  - sudo apt-get install -qq cloc
  - echo "Initialising default settings"
  - sed -i'' 's/tomcat.(TOMCAT_VERSION)/travis/' ./config/template/variable.makefile
  - sed -i'' 's/lr.common.theme = /lr.common.theme = \/tmp\/dspace/' ./config/local.conf.dist
  - sed -i'' 's/lr.dspace.dir = /lr.dspace.dir = \/tmp\/dspace/' ./config/local.conf.dist
  - "cd config && cp local.conf.dist local.conf && cd .."
  - "cd scripts"
  - echo "Creating dspace DB user and databases"
  - sudo -u postgres createuser --superuser dspace
  - make create_databases
  - echo "Installing prerequisites"
  - make setup

install:

before_script:

script:
  - make new_deploy
  - cloc ../
  - make print_message
  - make test_dspace_database
  - make test_utilities_database
  - make test_utilities_database
  - cd ../sources/dspace-api && mvn -Dmaven.test.skip=false -Dtest=cz.cuni.mff.ufal.dspace.**.*Test,cz.cuni.mff.ufal.*Test -DfailIfNoTests=false test && cd ../../
  - #make selenium_tests || echo "Tests failed"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1bd22d5970b8c5eb1d08
    on_success: change
    on_failure: always
    on_start: false